### ISSUE TITLE
Question about the how to set parameters for removing ground plane points?

### ISSUE THREAD

**Issue by LZL-CS** [jac99/Egonn#2]
Hi, thanks for your nice work.
I read your paper and found that you remove uninformative ground plane points with z coordinate below −0.9 m for the MulRan dataset and −1.6 m for the Apollo dataset. May I know how to set the parameters for removing ground plane points when I use other 3D point cloud data? 

Thanks in advance.

**Comment by jac99** [comment]
Hi, 
z_threshold depends on the LiDAR position with respect to the ground plane (the road).

For some datasets, you can get this value from extrinsic parameters included in the dataset. For others, you can find it by trial and error.
For Mulran and Apollo_SouthBay, we took a trial and error approach. We just tried different values of z_threshold - and for each z_threshold, we made a visualization of a few exemplary point clouds with all points with z-coordinates below z_threshold removed. When z_threshold was too low, a lot of ground plane points were visible. When it was too high, too many points from buildings were removed.
