### ISSUE TITLE
Exporting EgoNN model via TorchScript

### ISSUE THREAD

**Issue by mramezani64** [jac99/Egonn#4]
Dear Jacek, 
I'd like to export the EgoNN model in TorchScript format. 
At the moment, I get an error when loading the entire model. However, when loading only the weights in `torch.jit.script`, there is no problem. My impression is maybe TorchScript is not compatible with ME. If you have any insights on this issue, I appreciate it if you share them with me.
Thanks!

**Comment by jac99** [comment]
Hi Milad,

I suspect that MinkowskiEngine library may not be compatible with
TorchScript. It contains low-level CUDA kernels - for efficient sparse
convolutions. So likely it cannot be converted to TorchScript. But I don't
know how to help.

regards
Jacek Komorowski

pon., 7 lis 2022 o 08:01 Milad Ramezani ***@***.***>
napisał(a):

**Comment by jac99** [comment]
Closing
